models:
  embedding:
    name: "speechbrain/spkrec-ecapa-voxceleb"
    model_path: ""
    device: 0
  whisper:
    name: "faster-whisper-small"
    model_path: ""
    device: 0
    generation_config:
      language: "en"
      beam_size: 5
      best_of: 5